apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./Infrastructure/Kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: jimshao1999/blog_frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: jimshao1999/blog_event-bus
      context: EventBus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jimshao1999/blog_comment-service
      context: CommentService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jimshao1999/blog_post-service
      context: PostService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jimshao1999/blog_query-service
      context: QueryService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jimshao1999/blog_moderation-service
      context: ModerationService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .